name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'

    - name: Debug - Check npm version and fix if needed
      run: |
        echo "=== Node and npm versions ==="
        node --version
        npm --version
        echo "=== Try to install latest npm ==="
        npm install -g npm@latest
        npm --version
        echo "=== Check package-lock.json ==="
        head -10 package-lock.json
      working-directory: ./web

    - name: Install dependencies
      run: npm ci
      working-directory: ./web

    - name: Build
      run: npm run build
      working-directory: ./web

    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './web/dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
